#!/usr/bin/env python3
"""Export repetition-code golden vectors from relay_bp.

1) repetition_code.json — gamma0=None (plain BP, MinSumBPDecoderFixed).
   Cross-checked against Rust decode_repetition_code_int.
2) repetition_code_dmem.json — gamma0=0.1 (DMem-BP, MinSumBPDecoderFixed).
   Sanity-check only (cross_checked=false).
3) repetition_code_relay.json — full Relay-BP-SS via RelayDecoderF32
   (gamma0=0.1, num_sets=3, S=1). Also emits device/leg_gamma_table.gen.hpp.
   Historical fixed-point files (1)/(2) are left untouched as artifacts.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any, Optional

import numpy as np
from scipy.sparse import csr_matrix

# Hardcoded expected values from decode_repetition_code_int (must match exactly).
RUST_EXPECTED = [
    {
        "name": "no_error",
        "detectors": [0, 0],
        "expected_decoding": [0, 0, 0],
        "success": True,
    },
    {
        "name": "error_qubit_0",
        "detectors": [1, 0],
        "expected_decoding": [1, 0, 0],
        "success": True,
    },
    {
        "name": "error_qubit_1",
        "detectors": [1, 1],
        "expected_decoding": [0, 1, 0],
        "success": True,
    },
    {
        "name": "error_qubit_2",
        "detectors": [0, 1],
        "expected_decoding": [0, 0, 1],
        "success": True,
    },
]

# Must match ahls/device/min_sum_bp_types.hpp.
GAMMA0 = 0.1
PRE_ITER = 10
NUM_SETS = 3
SET_MAX_ITER = 10
STOP_NCONV = 1
GAMMA_DIST_INTERVAL = (-0.24, 0.66)
GAMMA_SEED = 0


def _repo_paths() -> tuple[Path, Path, Path]:
    script_dir = Path(__file__).resolve().parent
    ahls_root = script_dir.parent
    out_dir = ahls_root / "test" / "golden"
    device_dir = ahls_root / "device"
    return ahls_root, out_dir, device_dir


def make_explicit_gammas() -> np.ndarray:
    """Canonical 3x3 table: Uniform(gamma_dist_interval), seed=0.

    Passed to RelayDecoderF32 as explicit_gammas. Rust init_next_set(set_idx)
    indexes row (set_idx % num_sets), with set_idx in 1..=num_sets.
    """
    rng = np.random.default_rng(GAMMA_SEED)
    return rng.uniform(
        GAMMA_DIST_INTERVAL[0], GAMMA_DIST_INTERVAL[1], size=(NUM_SETS, 3)
    )


def make_leg_gamma(explicit: np.ndarray) -> list[list[float]]:
    """Effective kLegGamma[leg][*] as consumed by the SYCL kernel."""
    rows: list[list[float]] = [[GAMMA0, GAMMA0, GAMMA0]]
    for leg in range(1, 1 + NUM_SETS):
        rows.append([float(x) for x in explicit[leg % NUM_SETS]])
    return rows


def emit_leg_gamma_header(path: Path, leg_gamma: list[list[float]]) -> None:
    lines = [
        "// DO NOT EDIT — generated by scripts/export_golden_vectors.py",
        "// Per-leg memory strengths kLegGamma[kNumLegs][kNVar].",
        "// Leg 0 = uniform gamma0; legs 1..3 = explicit_gammas[leg % num_sets]",
        "// matching rust RelayDecoder::init_next_set(set_idx).",
        "#ifndef LEG_GAMMA_TABLE_GEN_HPP",
        "#define LEG_GAMMA_TABLE_GEN_HPP",
        "",
        "constexpr float kLegGamma[kNumLegs][kNVar] = {",
    ]
    for leg, row in enumerate(leg_gamma):
        vals = ", ".join(f"{v:.17g}f" for v in row)
        comma = "," if leg + 1 < len(leg_gamma) else ""
        lines.append(f"    {{{vals}}}{comma}  // leg {leg}")
    lines += ["};", "", "#endif", ""]
    path.write_text("\n".join(lines))
    print(f"Wrote {path}")


def build_decoder(gamma0: Optional[float] = None):
    import relay_bp

    check_dense = np.array([[1, 1, 0], [0, 1, 1]], dtype=np.uint8)
    error_priors = np.array([0.003, 0.003, 0.003], dtype=np.float64)
    int_bits = 5
    frac_bits = 2
    # Matches MinSumDecoderConfig::set_fixed(5, 2): max_data_value = 2^(int_bits-1).
    max_data_value = float(1 << (int_bits - 1))
    max_iter = 10

    kwargs: dict[str, Any] = {
        "max_iter": max_iter,
        "int_bits": int_bits,
        "frac_bits": frac_bits,
        "max_data_value": max_data_value,
    }
    if gamma0 is not None:
        kwargs["gamma0"] = gamma0

    decoder = relay_bp.MinSumBPDecoderFixed(
        csr_matrix(check_dense),
        error_priors=error_priors,
        **kwargs,
    )
    return decoder, {
        "check_matrix": check_dense.tolist(),
        "error_priors": error_priors.tolist(),
        "fixed_point": {
            "int_bits": int_bits,
            "frac_bits": frac_bits,
            "max_data_value": max_data_value,
            "max_iter": max_iter,
            "alpha": 1.0,
            "gamma0": gamma0,
            "data_scale_value": None,
        },
        "log_prior_ratios": np.log((1.0 - error_priors) / error_priors).tolist(),
    }


def build_relay_decoder(explicit_gammas: np.ndarray):
    import relay_bp

    check_dense = np.array([[1, 1, 0], [0, 1, 1]], dtype=np.uint8)
    error_priors = np.array([0.003, 0.003, 0.003], dtype=np.float64)

    decoder = relay_bp.RelayDecoderF32(
        csr_matrix(check_dense),
        error_priors=error_priors,
        gamma0=GAMMA0,
        pre_iter=PRE_ITER,
        num_sets=NUM_SETS,
        set_max_iter=SET_MAX_ITER,
        explicit_gammas=np.asarray(explicit_gammas, dtype=np.float64),
        stop_nconv=STOP_NCONV,
        stopping_criterion="nconv",
        seed=GAMMA_SEED,
    )
    meta = {
        "check_matrix": check_dense.tolist(),
        "error_priors": error_priors.tolist(),
        "numeric_type": "float32",
        "log_prior_ratios": np.log((1.0 - error_priors) / error_priors).tolist(),
        "relay_config": {
            "gamma0": GAMMA0,
            "pre_iter": PRE_ITER,
            "num_sets": NUM_SETS,
            "set_max_iter": SET_MAX_ITER,
            "stop_nconv": STOP_NCONV,
            "stopping_criterion": "nconv",
            "gamma_dist_interval": list(GAMMA_DIST_INTERVAL),
            "gamma_seed": GAMMA_SEED,
            "explicit_gammas": explicit_gammas.tolist(),
            "leg_gamma": make_leg_gamma(explicit_gammas),
        },
    }
    return decoder, meta


def _decode_vectors(decoder) -> list[dict[str, Any]]:
    vectors = []
    for spec in RUST_EXPECTED:
        detectors = np.array(spec["detectors"], dtype=np.uint8)
        result = decoder.decode_detailed(detectors)
        vectors.append(
            {
                "name": spec["name"],
                "detectors": spec["detectors"],
                "expected_decoding": [int(x) for x in result.decoding.tolist()],
                "expected_decoded_detectors": [
                    int(x) for x in result.decoded_detectors.tolist()
                ],
                "success": bool(result.success),
                "iterations": int(result.iterations),
                "max_iter": int(result.max_iter),
            }
        )
    return vectors


def _investigate_multi_leg_gap(decoder) -> dict[str, Any]:
    """Try to find a detector input that fails leg 0 so legs 1-3 run.

    On the 3-qubit repetition code BP converges in ~1 iteration for all
    weight-0/1 syndromes; there are no trapping sets. Document the gap.
    """
    note = (
        "Verification gap: repetition-code Relay goldens all converge within "
        "leg 0 (iterations <= pre_iter) for the 4 RUST_EXPECTED syndromes, so "
        "legs 1-3 (message reset + posterior carry) are not exercised. No "
        "synthetic 2-check detector was found that fails leg 0 without "
        "changing pre_iter/set_max_iter. Close in Phase 6 on surface-code "
        "d=7 / Gross [[144,12,12]], which have trapping sets."
    )
    # Exhaustive 2-bit syndromes already covered by RUST_EXPECTED.
    # Try random high-weight "fake" priors via a throwaway decoder is out of
    # scope (would change the golden config). Record observed iters instead.
    observed = []
    for spec in RUST_EXPECTED:
        detectors = np.array(spec["detectors"], dtype=np.uint8)
        result = decoder.decode_detailed(detectors)
        observed.append(
            {
                "name": spec["name"],
                "iterations": int(result.iterations),
                "success": bool(result.success),
            }
        )
    multi_leg = any(o["iterations"] > PRE_ITER for o in observed)
    return {
        "multi_leg_exercised": multi_leg,
        "observed": observed,
        "note": note,
    }


def export_plain(out_path: Path) -> None:
    decoder, meta = build_decoder(gamma0=None)
    vectors = _decode_vectors(decoder)

    mismatches = []
    for spec, v in zip(RUST_EXPECTED, vectors):
        if v["expected_decoding"] != spec["expected_decoding"] or v["success"] != spec["success"]:
            mismatches.append(
                {
                    "name": spec["name"],
                    "detectors": spec["detectors"],
                    "rust_decoding": spec["expected_decoding"],
                    "relay_bp_decoding": v["expected_decoding"],
                    "rust_success": spec["success"],
                    "relay_bp_success": v["success"],
                }
            )

    if mismatches:
        print("CROSS-CHECK FAILED against Rust decode_repetition_code_int:", file=sys.stderr)
        print(json.dumps(mismatches, indent=2), file=sys.stderr)
        raise SystemExit(1)

    payload = {
        "code": "repetition_3",
        "source": "relay_bp.MinSumBPDecoderFixed + rust decode_repetition_code_int",
        "cross_checked": True,
        "cross_check_oracle": "rust decode_repetition_code_int (gamma0=None)",
        **meta,
        "vectors": vectors,
    }
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(json.dumps(payload, indent=2) + "\n")
    print(f"Wrote {out_path}")
    print(f"Cross-check: all {len(vectors)} vectors match Rust expected decodings.")
    for v in vectors:
        print(
            f"  {v['name']}: detectors={v['detectors']} -> "
            f"decoding={v['expected_decoding']} success={v['success']} "
            f"iters={v['iterations']}"
        )


def export_dmem(out_path: Path, gamma0: float = 0.1) -> None:
    """gamma0!=None: no hardcoded Rust oracle for this repetition-code case."""
    decoder, meta = build_decoder(gamma0=gamma0)
    vectors = _decode_vectors(decoder)

    failed = [v for v in vectors if not v["success"]]
    if failed:
        print(
            "DMEM SANITY-CHECK FAILED: expected all 4 vectors to succeed "
            f"with gamma0={gamma0} (no trapping sets on this code):",
            file=sys.stderr,
        )
        print(json.dumps(failed, indent=2), file=sys.stderr)
        raise SystemExit(1)

    payload = {
        "code": "repetition_3",
        "source": "relay_bp.MinSumBPDecoderFixed(gamma0=0.1)",
        "cross_checked": False,
        "cross_check_oracle": None,
        "cross_check_note": (
            "No hardcoded Rust test covers gamma0!=None for the 3-qubit "
            "repetition code. Vectors come from relay_bp.MinSumBPDecoderFixed "
            f"with gamma0={gamma0}. Sanity-check only: all 4 inputs decoded "
            "successfully (this code has no trapping sets)."
        ),
        **meta,
        "vectors": vectors,
    }
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(json.dumps(payload, indent=2) + "\n")
    print(f"Wrote {out_path}")
    print(
        f"DMem-BP gamma0={gamma0}: cross_checked=false "
        f"(no second Rust oracle). Sanity-check: all {len(vectors)} succeeded."
    )
    for v in vectors:
        print(
            f"  {v['name']}: detectors={v['detectors']} -> "
            f"decoding={v['expected_decoding']} success={v['success']} "
            f"iters={v['iterations']}"
        )


def export_relay(out_path: Path, gen_hpp: Path) -> None:
    explicit = make_explicit_gammas()
    leg_gamma = make_leg_gamma(explicit)
    emit_leg_gamma_header(gen_hpp, leg_gamma)

    decoder, meta = build_relay_decoder(explicit)
    vectors = _decode_vectors(decoder)
    gap = _investigate_multi_leg_gap(decoder)

    failed = [v for v in vectors if not v["success"]]
    if failed:
        print(
            "RELAY SANITY-CHECK FAILED: expected all 4 vectors to succeed:",
            file=sys.stderr,
        )
        print(json.dumps(failed, indent=2), file=sys.stderr)
        raise SystemExit(1)

    # Soft check vs RUST_EXPECTED decodings (same syndromes; Relay should agree).
    for spec, v in zip(RUST_EXPECTED, vectors):
        if v["expected_decoding"] != spec["expected_decoding"]:
            print(
                f"WARNING: {v['name']} decoding {v['expected_decoding']} "
                f"!= Rust expected {spec['expected_decoding']}",
                file=sys.stderr,
            )

    payload = {
        "code": "repetition_3",
        "source": (
            "relay_bp.RelayDecoderF32(gamma0=0.1, pre_iter=10, num_sets=3, "
            "set_max_iter=10, explicit_gammas=Uniform(-0.24,0.66) seed=0, "
            "stop_nconv=1, stopping_criterion=nconv)"
        ),
        "cross_checked": False,
        "cross_check_oracle": None,
        "cross_check_note": (
            "No independent Rust #[test] oracle exists for this exact multi-leg "
            "RelayDecoderF32 config on the 3-qubit repetition code. Vectors come "
            "from relay_bp.RelayDecoderF32 with the config below. Sanity-check: "
            "all 4 RUST_EXPECTED syndromes decode successfully."
        ),
        "verification_gap": gap,
        **meta,
        "vectors": vectors,
    }
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(json.dumps(payload, indent=2) + "\n")
    print(f"Wrote {out_path}")
    print(
        "Relay-BP-SS: cross_checked=false. "
        f"Sanity-check: all {len(vectors)} succeeded. "
        f"multi_leg_exercised={gap['multi_leg_exercised']}"
    )
    for v in vectors:
        print(
            f"  {v['name']}: detectors={v['detectors']} -> "
            f"decoding={v['expected_decoding']} success={v['success']} "
            f"iters={v['iterations']}"
        )
    print(gap["note"])


def main() -> None:
    _, default_out_dir, device_dir = _repo_paths()
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "-o",
        "--output",
        type=Path,
        default=default_out_dir / "repetition_code.json",
        help="Output JSON path for the gamma0=None (plain BP) vectors",
    )
    parser.add_argument(
        "--dmem-output",
        type=Path,
        default=default_out_dir / "repetition_code_dmem.json",
        help="Output JSON path for the gamma0=0.1 (DMem-BP) vectors",
    )
    parser.add_argument(
        "--relay-output",
        type=Path,
        default=default_out_dir / "repetition_code_relay.json",
        help="Output JSON path for Relay-BP-SS (RelayDecoderF32) vectors",
    )
    parser.add_argument(
        "--leg-gamma-hpp",
        type=Path,
        default=device_dir / "leg_gamma_table.gen.hpp",
        help="Generated C++ header for kLegGamma",
    )
    parser.add_argument(
        "--skip-fixed-point",
        action="store_true",
        help="Only export Relay-BP-SS golden + leg_gamma header",
    )
    args = parser.parse_args()
    if not args.skip_fixed_point:
        export_plain(args.output.resolve())
        export_dmem(args.dmem_output.resolve())
    export_relay(args.relay_output.resolve(), args.leg_gamma_hpp.resolve())


if __name__ == "__main__":
    main()
