#!/usr/bin/env python3
"""Export repetition-code golden vectors from relay_bp.

1) repetition_code.json — gamma0=None (plain BP, MinSumBPDecoderFixed).
   Cross-checked against Rust decode_repetition_code_int.
2) repetition_code_dmem.json — gamma0=0.1 (DMem-BP, MinSumBPDecoderFixed).
   Sanity-check only (cross_checked=false).
3) repetition_code_relay.json — full Relay-BP-SS via RelayDecoderF32
   (gamma0=0.1, num_sets=3, S=1, pre_iter=10). Also emits
   device/leg_gamma_table.gen.hpp (float + i32 Q-scale tables).
4) repetition_code_relay_multileg.json — same config with pre_iter=1 so
   error_qubit_1 is forced through leg 1 (reset msgs / carry posterior).
5) repetition_code_relay_i32.json / _multileg_i32.json — same Relay config
   via RelayDecoderI32(data_scale_value=256) for AHLS MsgT=int.
   Historical fixed-point files (1)/(2) are left untouched as artifacts.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any, Optional

import numpy as np
from scipy.sparse import csr_matrix

# Hardcoded expected values from decode_repetition_code_int (must match exactly).
RUST_EXPECTED = [
    {
        "name": "no_error",
        "detectors": [0, 0],
        "expected_decoding": [0, 0, 0],
        "success": True,
    },
    {
        "name": "error_qubit_0",
        "detectors": [1, 0],
        "expected_decoding": [1, 0, 0],
        "success": True,
    },
    {
        "name": "error_qubit_1",
        "detectors": [1, 1],
        "expected_decoding": [0, 1, 0],
        "success": True,
    },
    {
        "name": "error_qubit_2",
        "detectors": [0, 1],
        "expected_decoding": [0, 0, 1],
        "success": True,
    },
]

# Must match ahls/device/relay_bp_types.hpp (production defaults).
GAMMA0 = 0.1
PRE_ITER = 10
PRE_ITER_MULTILEG = 1  # KPRE_ITER_OVERRIDE=1 regression build
NUM_SETS = 3
SET_MAX_ITER = 10
STOP_NCONV = 1
GAMMA_DIST_INTERVAL = (-0.24, 0.66)
GAMMA_SEED = 0


def _repo_paths() -> tuple[Path, Path, Path]:
    script_dir = Path(__file__).resolve().parent
    ahls_root = script_dir.parent
    out_dir = ahls_root / "test" / "golden"
    device_dir = ahls_root / "device"
    return ahls_root, out_dir, device_dir


def make_explicit_gammas() -> np.ndarray:
    """Canonical 3x3 table: Uniform(gamma_dist_interval), seed=0.

    Passed to RelayDecoderF32 as explicit_gammas. Rust init_next_set(set_idx)
    indexes row (set_idx % num_sets), with set_idx in 1..=num_sets.
    """
    rng = np.random.default_rng(GAMMA_SEED)
    return rng.uniform(
        GAMMA_DIST_INTERVAL[0], GAMMA_DIST_INTERVAL[1], size=(NUM_SETS, 3)
    )


def make_leg_gamma(explicit: np.ndarray) -> list[list[float]]:
    """Effective kLegGamma[leg][*] as consumed by the SYCL kernel."""
    rows: list[list[float]] = [[GAMMA0, GAMMA0, GAMMA0]]
    for leg in range(1, 1 + NUM_SETS):
        rows.append([float(x) for x in explicit[leg % NUM_SETS]])
    return rows


# Fixed-point scale matching RelayDecoderI32 data_scale_value (Q8).
DATA_SCALE = 256


def to_i32_trunc(x: float) -> int:
    """Match Rust `as i32` / FromPrimitive::from_f64: truncate toward zero."""
    return int(x)


def scale_f64_to_i32(x: float, scale: int = DATA_SCALE) -> int:
    return to_i32_trunc(scale * x)


def make_leg_gamma_q(
    leg_gamma: list[list[float]], scale: int = DATA_SCALE
) -> list[list[int]]:
    return [[scale_f64_to_i32(x, scale) for x in row] for row in leg_gamma]


def emit_leg_gamma_header(path: Path, leg_gamma: list[list[float]]) -> None:
    leg_q = make_leg_gamma_q(leg_gamma)
    lines = [
        "// DO NOT EDIT — generated by scripts/export_golden_vectors.py",
        "// Per-leg memory strengths kLegGamma[kNumLegs][kNVar].",
        "// Leg 0 = uniform gamma0; legs 1..3 = explicit_gammas[leg % num_sets]",
        "// matching rust RelayDecoder::init_next_set(set_idx).",
        "// kLegGammaQ = trunc(DATA_SCALE * kLegGamma) toward zero (Rust i32).",
        "#ifndef LEG_GAMMA_TABLE_GEN_HPP",
        "#define LEG_GAMMA_TABLE_GEN_HPP",
        "",
        f"constexpr int kGammaQScale = {DATA_SCALE};",
        "",
        "constexpr float kLegGamma[kNumLegs][kNVar] = {",
    ]
    for leg, row in enumerate(leg_gamma):
        vals = ", ".join(f"{v:.17g}f" for v in row)
        comma = "," if leg + 1 < len(leg_gamma) else ""
        lines.append(f"    {{{vals}}}{comma}  // leg {leg}")
    lines += [
        "};",
        "",
        "constexpr int kLegGammaQ[kNumLegs][kNVar] = {",
    ]
    for leg, row in enumerate(leg_q):
        vals = ", ".join(str(v) for v in row)
        comma = "," if leg + 1 < len(leg_q) else ""
        lines.append(f"    {{{vals}}}{comma}  // leg {leg}")
    lines += ["};", "", "#endif", ""]
    path.write_text("\n".join(lines))
    print(f"Wrote {path}")


def build_decoder(gamma0: Optional[float] = None):
    import relay_bp

    check_dense = np.array([[1, 1, 0], [0, 1, 1]], dtype=np.uint8)
    error_priors = np.array([0.003, 0.003, 0.003], dtype=np.float64)
    int_bits = 5
    frac_bits = 2
    # Matches MinSumDecoderConfig::set_fixed(5, 2): max_data_value = 2^(int_bits-1).
    max_data_value = float(1 << (int_bits - 1))
    max_iter = 10

    kwargs: dict[str, Any] = {
        "max_iter": max_iter,
        "int_bits": int_bits,
        "frac_bits": frac_bits,
        "max_data_value": max_data_value,
    }
    if gamma0 is not None:
        kwargs["gamma0"] = gamma0

    decoder = relay_bp.MinSumBPDecoderFixed(
        csr_matrix(check_dense),
        error_priors=error_priors,
        **kwargs,
    )
    return decoder, {
        "check_matrix": check_dense.tolist(),
        "error_priors": error_priors.tolist(),
        "fixed_point": {
            "int_bits": int_bits,
            "frac_bits": frac_bits,
            "max_data_value": max_data_value,
            "max_iter": max_iter,
            "alpha": 1.0,
            "gamma0": gamma0,
            "data_scale_value": None,
        },
        "log_prior_ratios": np.log((1.0 - error_priors) / error_priors).tolist(),
    }


def build_relay_decoder(explicit_gammas: np.ndarray, pre_iter: int = PRE_ITER):
    import relay_bp

    check_dense = np.array([[1, 1, 0], [0, 1, 1]], dtype=np.uint8)
    error_priors = np.array([0.003, 0.003, 0.003], dtype=np.float64)

    decoder = relay_bp.RelayDecoderF32(
        csr_matrix(check_dense),
        error_priors=error_priors,
        gamma0=GAMMA0,
        pre_iter=pre_iter,
        num_sets=NUM_SETS,
        set_max_iter=SET_MAX_ITER,
        explicit_gammas=np.asarray(explicit_gammas, dtype=np.float64),
        stop_nconv=STOP_NCONV,
        stopping_criterion="nconv",
        seed=GAMMA_SEED,
    )
    meta = {
        "check_matrix": check_dense.tolist(),
        "error_priors": error_priors.tolist(),
        "numeric_type": "float32",
        "log_prior_ratios": np.log((1.0 - error_priors) / error_priors).tolist(),
        "relay_config": {
            "gamma0": GAMMA0,
            "pre_iter": pre_iter,
            "num_sets": NUM_SETS,
            "set_max_iter": SET_MAX_ITER,
            "stop_nconv": STOP_NCONV,
            "stopping_criterion": "nconv",
            "gamma_dist_interval": list(GAMMA_DIST_INTERVAL),
            "gamma_seed": GAMMA_SEED,
            "explicit_gammas": explicit_gammas.tolist(),
            "leg_gamma": make_leg_gamma(explicit_gammas),
        },
    }
    return decoder, meta


def build_relay_decoder_i32(
    explicit_gammas: np.ndarray, pre_iter: int = PRE_ITER, scale: int = DATA_SCALE
):
    """RelayDecoderI32 with data_scale_value=scale (AHLS MsgT=int path)."""
    import relay_bp

    check_dense = np.array([[1, 1, 0], [0, 1, 1]], dtype=np.uint8)
    error_priors = np.array([0.003, 0.003, 0.003], dtype=np.float64)
    log_priors = np.log((1.0 - error_priors) / error_priors)
    log_priors_i32 = [scale_f64_to_i32(float(x), scale) for x in log_priors]
    leg_gamma = make_leg_gamma(explicit_gammas)
    leg_gamma_q = make_leg_gamma_q(leg_gamma, scale)

    decoder = relay_bp.RelayDecoderI32(
        csr_matrix(check_dense),
        error_priors=error_priors,
        gamma0=GAMMA0,
        pre_iter=pre_iter,
        num_sets=NUM_SETS,
        set_max_iter=SET_MAX_ITER,
        explicit_gammas=np.asarray(explicit_gammas, dtype=np.float64),
        stop_nconv=STOP_NCONV,
        stopping_criterion="nconv",
        seed=GAMMA_SEED,
        data_scale_value=float(scale),
    )
    meta = {
        "check_matrix": check_dense.tolist(),
        "error_priors": error_priors.tolist(),
        "numeric_type": "int32",
        "data_scale_value": scale,
        "log_prior_ratios": log_priors.tolist(),
        "log_prior_ratios_i32": log_priors_i32,
        "relay_config": {
            "gamma0": GAMMA0,
            "pre_iter": pre_iter,
            "num_sets": NUM_SETS,
            "set_max_iter": SET_MAX_ITER,
            "stop_nconv": STOP_NCONV,
            "stopping_criterion": "nconv",
            "data_scale_value": scale,
            "gamma_dist_interval": list(GAMMA_DIST_INTERVAL),
            "gamma_seed": GAMMA_SEED,
            "explicit_gammas": explicit_gammas.tolist(),
            "leg_gamma": leg_gamma,
            "leg_gamma_q": leg_gamma_q,
        },
    }
    return decoder, meta


def _decode_vectors(decoder) -> list[dict[str, Any]]:
    vectors = []
    for spec in RUST_EXPECTED:
        detectors = np.array(spec["detectors"], dtype=np.uint8)
        result = decoder.decode_detailed(detectors)
        vectors.append(
            {
                "name": spec["name"],
                "detectors": spec["detectors"],
                "expected_decoding": [int(x) for x in result.decoding.tolist()],
                "expected_decoded_detectors": [
                    int(x) for x in result.decoded_detectors.tolist()
                ],
                "success": bool(result.success),
                "iterations": int(result.iterations),
                "max_iter": int(result.max_iter),
            }
        )
    return vectors


def _leg_reached(total_iters: int, pre_iter: int) -> int:
    """Infer the highest leg index entered from total iterations (S=1)."""
    if total_iters <= pre_iter:
        return 0
    remaining = total_iters - pre_iter
    # Legs 1.. use set_max_iter each; with S=1 we stop on first success.
    return 1 + (remaining - 1) // SET_MAX_ITER


def export_plain(out_path: Path) -> None:
    decoder, meta = build_decoder(gamma0=None)
    vectors = _decode_vectors(decoder)

    mismatches = []
    for spec, v in zip(RUST_EXPECTED, vectors):
        if v["expected_decoding"] != spec["expected_decoding"] or v["success"] != spec["success"]:
            mismatches.append(
                {
                    "name": spec["name"],
                    "detectors": spec["detectors"],
                    "rust_decoding": spec["expected_decoding"],
                    "relay_bp_decoding": v["expected_decoding"],
                    "rust_success": spec["success"],
                    "relay_bp_success": v["success"],
                }
            )

    if mismatches:
        print("CROSS-CHECK FAILED against Rust decode_repetition_code_int:", file=sys.stderr)
        print(json.dumps(mismatches, indent=2), file=sys.stderr)
        raise SystemExit(1)

    payload = {
        "code": "repetition_3",
        "source": "relay_bp.MinSumBPDecoderFixed + rust decode_repetition_code_int",
        "cross_checked": True,
        "cross_check_oracle": "rust decode_repetition_code_int (gamma0=None)",
        **meta,
        "vectors": vectors,
    }
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(json.dumps(payload, indent=2) + "\n")
    print(f"Wrote {out_path}")
    print(f"Cross-check: all {len(vectors)} vectors match Rust expected decodings.")
    for v in vectors:
        print(
            f"  {v['name']}: detectors={v['detectors']} -> "
            f"decoding={v['expected_decoding']} success={v['success']} "
            f"iters={v['iterations']}"
        )


def export_dmem(out_path: Path, gamma0: float = 0.1) -> None:
    """gamma0!=None: no hardcoded Rust oracle for this repetition-code case."""
    decoder, meta = build_decoder(gamma0=gamma0)
    vectors = _decode_vectors(decoder)

    failed = [v for v in vectors if not v["success"]]
    if failed:
        print(
            "DMEM SANITY-CHECK FAILED: expected all 4 vectors to succeed "
            f"with gamma0={gamma0} (no trapping sets on this code):",
            file=sys.stderr,
        )
        print(json.dumps(failed, indent=2), file=sys.stderr)
        raise SystemExit(1)

    payload = {
        "code": "repetition_3",
        "source": "relay_bp.MinSumBPDecoderFixed(gamma0=0.1)",
        "cross_checked": False,
        "cross_check_oracle": None,
        "cross_check_note": (
            "No hardcoded Rust test covers gamma0!=None for the 3-qubit "
            "repetition code. Vectors come from relay_bp.MinSumBPDecoderFixed "
            f"with gamma0={gamma0}. Sanity-check only: all 4 inputs decoded "
            "successfully (this code has no trapping sets)."
        ),
        **meta,
        "vectors": vectors,
    }
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(json.dumps(payload, indent=2) + "\n")
    print(f"Wrote {out_path}")
    print(
        f"DMem-BP gamma0={gamma0}: cross_checked=false "
        f"(no second Rust oracle). Sanity-check: all {len(vectors)} succeeded."
    )
    for v in vectors:
        print(
            f"  {v['name']}: detectors={v['detectors']} -> "
            f"decoding={v['expected_decoding']} success={v['success']} "
            f"iters={v['iterations']}"
        )


def export_relay(out_path: Path, gen_hpp: Path) -> None:
    explicit = make_explicit_gammas()
    leg_gamma = make_leg_gamma(explicit)
    emit_leg_gamma_header(gen_hpp, leg_gamma)

    decoder, meta = build_relay_decoder(explicit, pre_iter=PRE_ITER)
    vectors = _decode_vectors(decoder)

    failed = [v for v in vectors if not v["success"]]
    if failed:
        print(
            "RELAY SANITY-CHECK FAILED: expected all 4 vectors to succeed:",
            file=sys.stderr,
        )
        print(json.dumps(failed, indent=2), file=sys.stderr)
        raise SystemExit(1)

    # Soft check vs RUST_EXPECTED decodings (same syndromes; Relay should agree).
    for spec, v in zip(RUST_EXPECTED, vectors):
        if v["expected_decoding"] != spec["expected_decoding"]:
            print(
                f"WARNING: {v['name']} decoding {v['expected_decoding']} "
                f"!= Rust expected {spec['expected_decoding']}",
                file=sys.stderr,
            )

    observed = [
        {
            "name": v["name"],
            "iterations": v["iterations"],
            "success": v["success"],
            "leg_reached": _leg_reached(v["iterations"], PRE_ITER),
        }
        for v in vectors
    ]
    # Production pre_iter=10: all vectors stay on leg 0; multi-leg path is
    # covered by repetition_code_relay_multileg.json (pre_iter=1).
    gap = {
        "multi_leg_exercised": False,
        "observed": observed,
        "note": (
            "Production pre_iter=10 goldens all converge within leg 0. The "
            "leg-transition path (reset v2c/c2v, carry posterior_prev) is "
            "closed by the dedicated regression golden "
            "repetition_code_relay_multileg.json (same decoder, pre_iter=1 / "
            "KPRE_ITER_OVERRIDE=1), which forces error_qubit_1 through leg 1."
        ),
        "closed_by": "test/golden/repetition_code_relay_multileg.json",
    }

    payload = {
        "code": "repetition_3",
        "source": (
            "relay_bp.RelayDecoderF32(gamma0=0.1, pre_iter=10, num_sets=3, "
            "set_max_iter=10, explicit_gammas=Uniform(-0.24,0.66) seed=0, "
            "stop_nconv=1, stopping_criterion=nconv)"
        ),
        "cross_checked": False,
        "cross_check_oracle": None,
        "cross_check_note": (
            "No independent Rust #[test] oracle exists for this exact multi-leg "
            "RelayDecoderF32 config on the 3-qubit repetition code. Vectors come "
            "from relay_bp.RelayDecoderF32 with the config below. Sanity-check: "
            "all 4 RUST_EXPECTED syndromes decode successfully."
        ),
        "verification_gap": gap,
        **meta,
        "vectors": vectors,
    }
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(json.dumps(payload, indent=2) + "\n")
    print(f"Wrote {out_path}")
    print(
        "Relay-BP-SS: cross_checked=false. "
        f"Sanity-check: all {len(vectors)} succeeded. "
        f"multi_leg_exercised={gap['multi_leg_exercised']} "
        f"(closed_by={gap['closed_by']})"
    )
    for v in vectors:
        print(
            f"  {v['name']}: detectors={v['detectors']} -> "
            f"decoding={v['expected_decoding']} success={v['success']} "
            f"iters={v['iterations']}"
        )


def export_relay_multileg(out_path: Path) -> None:
    """Same Relay config as export_relay but pre_iter=1 to force leg 1.

    Premise: under pre_iter=10, error_qubit_1 needs 2 iterations; with
    pre_iter=1, leg 0 cannot finish that work, so the decoder enters leg 1.
    """
    explicit = make_explicit_gammas()
    leg_gamma = make_leg_gamma(explicit)
    decoder, meta = build_relay_decoder(explicit, pre_iter=PRE_ITER_MULTILEG)
    vectors = _decode_vectors(decoder)

    failed = [v for v in vectors if not v["success"]]
    if failed:
        print(
            "RELAY MULTILEG SANITY-CHECK FAILED: expected all 4 to succeed:",
            file=sys.stderr,
        )
        print(json.dumps(failed, indent=2), file=sys.stderr)
        raise SystemExit(1)

    multi_leg_vectors = []
    for v in vectors:
        leg = _leg_reached(v["iterations"], PRE_ITER_MULTILEG)
        entry = {
            "name": v["name"],
            "iterations": v["iterations"],
            "leg_reached": leg,
            "leg_gamma_row": leg_gamma[leg],
        }
        if v["iterations"] > PRE_ITER_MULTILEG:
            multi_leg_vectors.append(entry)

    if not multi_leg_vectors:
        print(
            "RELAY MULTILEG PREMISE FAILED: none of the 4 vectors needed "
            f"more than pre_iter={PRE_ITER_MULTILEG} iteration(s). "
            "error_qubit_1 was expected to enter leg 1; investigate.",
            file=sys.stderr,
        )
        print(json.dumps(vectors, indent=2), file=sys.stderr)
        raise SystemExit(1)

    note = (
        f"Regression golden: identical to repetition_code_relay.json except "
        f"pre_iter={PRE_ITER_MULTILEG} (matches -DKPRE_ITER_OVERRIDE=1). "
        f"Vectors with iterations > {PRE_ITER_MULTILEG} entered leg >= 1, "
        f"exercising message reset + posterior carry. "
        f"Leg-transition vectors: "
        + ", ".join(
            f"{e['name']} (iters={e['iterations']}, leg={e['leg_reached']}, "
            f"gamma={e['leg_gamma_row']})"
            for e in multi_leg_vectors
        )
    )

    payload = {
        "code": "repetition_3",
        "source": (
            f"relay_bp.RelayDecoderF32(gamma0=0.1, pre_iter={PRE_ITER_MULTILEG}, "
            "num_sets=3, set_max_iter=10, explicit_gammas=Uniform(-0.24,0.66) "
            "seed=0, stop_nconv=1, stopping_criterion=nconv)"
        ),
        "cross_checked": False,
        "cross_check_oracle": None,
        "cross_check_note": (
            "Dedicated multileg regression: same RelayDecoderF32 setup as "
            "repetition_code_relay.json with only pre_iter lowered to 1 so "
            "leg 0 fails on syndromes that need 2 BP iters under production "
            "config (error_qubit_1). Proves reset-messages / carry-posterior."
        ),
        "multileg_note": note,
        "multileg_vectors": multi_leg_vectors,
        **meta,
        "vectors": vectors,
    }
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(json.dumps(payload, indent=2) + "\n")
    print(f"Wrote {out_path}")
    print(f"Relay multileg: {len(multi_leg_vectors)} vector(s) entered leg>=1.")
    print(note)
    for v in vectors:
        print(
            f"  {v['name']}: detectors={v['detectors']} -> "
            f"decoding={v['expected_decoding']} success={v['success']} "
            f"iters={v['iterations']}"
        )


def export_relay_i32(out_path: Path) -> None:
    """AHLS MsgT=int oracle: RelayDecoderI32(data_scale_value=DATA_SCALE)."""
    explicit = make_explicit_gammas()
    decoder, meta = build_relay_decoder_i32(explicit, pre_iter=PRE_ITER)
    vectors = _decode_vectors(decoder)

    failed = [v for v in vectors if not v["success"]]
    if failed:
        print(
            "RELAY I32 SANITY-CHECK FAILED: expected all 4 vectors to succeed:",
            file=sys.stderr,
        )
        print(json.dumps(failed, indent=2), file=sys.stderr)
        raise SystemExit(1)

    for spec, v in zip(RUST_EXPECTED, vectors):
        if v["expected_decoding"] != spec["expected_decoding"]:
            print(
                f"WARNING: {v['name']} decoding {v['expected_decoding']} "
                f"!= RUST_EXPECTED {spec['expected_decoding']}",
                file=sys.stderr,
            )

    payload = {
        "code": "repetition_3",
        "source": (
            f"relay_bp.RelayDecoderI32(gamma0=0.1, pre_iter={PRE_ITER}, "
            f"num_sets={NUM_SETS}, set_max_iter={SET_MAX_ITER}, "
            f"data_scale_value={DATA_SCALE}, explicit_gammas=Uniform"
            f"{GAMMA_DIST_INTERVAL} seed={GAMMA_SEED}, stop_nconv={STOP_NCONV})"
        ),
        "cross_checked": True,
        "cross_check_oracle": "relay_bp.RelayDecoderI32",
        "cross_check_note": (
            "Vectors and log_prior_ratios_i32 / leg_gamma_q come from "
            f"RelayDecoderI32 with data_scale_value={DATA_SCALE}. AHLS MsgT=int "
            "must use the same scale and rust-style (λ/S)*(S-γ)+(M/S)*γ mix."
        ),
        **meta,
        "vectors": vectors,
    }
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(json.dumps(payload, indent=2) + "\n")
    print(f"Wrote {out_path}")
    print(
        f"Relay-BP-SS i32 (scale={DATA_SCALE}): cross_checked=true vs "
        f"RelayDecoderI32. All {len(vectors)} succeeded."
    )
    for v in vectors:
        print(
            f"  {v['name']}: detectors={v['detectors']} -> "
            f"decoding={v['expected_decoding']} success={v['success']} "
            f"iters={v['iterations']}"
        )


def export_relay_multileg_i32(out_path: Path) -> None:
    """i32 multileg regression (pre_iter=1), same scale as export_relay_i32."""
    explicit = make_explicit_gammas()
    leg_gamma = make_leg_gamma(explicit)
    decoder, meta = build_relay_decoder_i32(
        explicit, pre_iter=PRE_ITER_MULTILEG
    )
    vectors = _decode_vectors(decoder)

    failed = [v for v in vectors if not v["success"]]
    if failed:
        print(
            "RELAY I32 MULTILEG SANITY-CHECK FAILED:",
            file=sys.stderr,
        )
        print(json.dumps(failed, indent=2), file=sys.stderr)
        raise SystemExit(1)

    multi_leg_vectors = []
    for v in vectors:
        leg = _leg_reached(v["iterations"], PRE_ITER_MULTILEG)
        if v["iterations"] > PRE_ITER_MULTILEG:
            multi_leg_vectors.append(
                {
                    "name": v["name"],
                    "iterations": v["iterations"],
                    "leg_reached": leg,
                    "leg_gamma_row": leg_gamma[leg],
                    "leg_gamma_q_row": meta["relay_config"]["leg_gamma_q"][leg],
                }
            )

    if not multi_leg_vectors:
        print(
            "RELAY I32 MULTILEG PREMISE FAILED: no vector entered leg>=1.",
            file=sys.stderr,
        )
        raise SystemExit(1)

    payload = {
        "code": "repetition_3",
        "source": (
            f"relay_bp.RelayDecoderI32(pre_iter={PRE_ITER_MULTILEG}, "
            f"data_scale_value={DATA_SCALE}, …)"
        ),
        "cross_checked": True,
        "cross_check_oracle": "relay_bp.RelayDecoderI32",
        "cross_check_note": (
            f"i32 multileg regression: pre_iter={PRE_ITER_MULTILEG} with "
            f"data_scale_value={DATA_SCALE}; matches -DKPRE_ITER_OVERRIDE=1."
        ),
        "multileg_vectors": multi_leg_vectors,
        **meta,
        "vectors": vectors,
    }
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(json.dumps(payload, indent=2) + "\n")
    print(f"Wrote {out_path}")
    print(f"Relay i32 multileg: {len(multi_leg_vectors)} vector(s) entered leg>=1.")
    for v in vectors:
        print(
            f"  {v['name']}: detectors={v['detectors']} -> "
            f"decoding={v['expected_decoding']} success={v['success']} "
            f"iters={v['iterations']}"
        )


def main() -> None:
    _, default_out_dir, device_dir = _repo_paths()
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "-o",
        "--output",
        type=Path,
        default=default_out_dir / "repetition_code.json",
        help="Output JSON path for the gamma0=None (plain BP) vectors",
    )
    parser.add_argument(
        "--dmem-output",
        type=Path,
        default=default_out_dir / "repetition_code_dmem.json",
        help="Output JSON path for the gamma0=0.1 (DMem-BP) vectors",
    )
    parser.add_argument(
        "--relay-output",
        type=Path,
        default=default_out_dir / "repetition_code_relay.json",
        help="Output JSON path for Relay-BP-SS (RelayDecoderF32) vectors",
    )
    parser.add_argument(
        "--relay-multileg-output",
        type=Path,
        default=default_out_dir / "repetition_code_relay_multileg.json",
        help="Output JSON for pre_iter=1 multileg regression goldens",
    )
    parser.add_argument(
        "--relay-i32-output",
        type=Path,
        default=default_out_dir / "repetition_code_relay_i32.json",
        help="Output JSON for RelayDecoderI32 (data_scale=256) goldens",
    )
    parser.add_argument(
        "--relay-multileg-i32-output",
        type=Path,
        default=default_out_dir / "repetition_code_relay_multileg_i32.json",
        help="Output JSON for i32 multileg regression goldens",
    )
    parser.add_argument(
        "--leg-gamma-hpp",
        type=Path,
        default=device_dir / "leg_gamma_table.gen.hpp",
        help="Generated C++ header for kLegGamma / kLegGammaQ",
    )
    parser.add_argument(
        "--skip-fixed-point",
        action="store_true",
        help="Only export Relay-BP-SS goldens + leg_gamma header",
    )
    args = parser.parse_args()
    if not args.skip_fixed_point:
        export_plain(args.output.resolve())
        export_dmem(args.dmem_output.resolve())
    export_relay(args.relay_output.resolve(), args.leg_gamma_hpp.resolve())
    export_relay_multileg(args.relay_multileg_output.resolve())
    export_relay_i32(args.relay_i32_output.resolve())
    export_relay_multileg_i32(args.relay_multileg_i32_output.resolve())


if __name__ == "__main__":
    main()
