// Templated message type for the 3-qubit repetition-code Relay-BP decoder.
// Default MsgT = int32 with data_scale S=256, matching rust
// RelayDecoderI32(..., data_scale_value=256). Build with -DRELAY_MSG_T_FLOAT
// for RelayDecoderF32 / float32 goldens.
// See docs/env_setup_notes.md.

#ifndef RELAY_BP_TYPES_HPP
#define RELAY_BP_TYPES_HPP

#include <cmath>

constexpr int kNVar = 3;
constexpr int kNChk = 2;
constexpr int kMaxChkDeg = 2;
constexpr int kMaxVarDeg = 2;

// Relay-BP-SS (Algorithm 1 / RelayDecoder::decode_detailed):
//   R = kNumLegs = 1 + num_sets = 4  (leg 0 = first Mem-BP + 3 relay sets)
//   T_0 = kPreIter, T_{r>=1} = kSetMaxIter
//   S = kStopNConv = 1 (StoppingCriterion::NConv{stop_after:1})
constexpr int kNumRelaySets = 3;
constexpr int kNumLegs = 1 + kNumRelaySets;  // 4
#ifndef KPRE_ITER_OVERRIDE
constexpr int kPreIter = 10;
#else
constexpr int kPreIter = KPRE_ITER_OVERRIDE;
#endif
constexpr int kSetMaxIter = 10;
constexpr int kStopNConv = 1;
constexpr float kGamma0 = 0.1f;

// Dense H = [[1,1,0],[0,1,1]] as CSR (check -> vars) and CSC (var -> checks).
constexpr int kChkDeg[kNChk] = {2, 2};
constexpr int kChkVars[kNChk][kMaxChkDeg] = {{0, 1}, {1, 2}};

constexpr int kVarDeg[kNVar] = {1, 2, 1};
constexpr int kVarChecks[kNVar][kMaxVarDeg] = {{0, 0}, {0, 1}, {1, 0}};

// Per-leg γ (float) + Q-scale int table. Generated by export_golden_vectors.py
// to match RelayDecoderI32 data_scale_value (trunc toward zero like Rust
// `as i32` / FromPrimitive::from_f64).
#include "leg_gamma_table.gen.hpp"

// Fixed-point scale S: store x_int ≈ S * x_float (Rust data_scale_value).
constexpr int kDataScale = kGammaQScale;  // alias; defined in gen header

#if defined(RELAY_MSG_T_FLOAT)
using MsgT = float;
#else
using MsgT = int;
#endif

// Message helpers — overloads (not if-constexpr) for AHLS device code.
inline float msg_zero(float) { return 0.0f; }
inline int msg_zero(int) { return 0; }

inline float msg_one(float) { return 1.0f; }
inline int msg_one(int) { return 1; }

inline float msg_abs(float x) { return fabsf(x); }
inline int msg_abs(int x) { return x < 0 ? -x : x; }

inline bool msg_is_neg(float x) { return x < 0.0f; }
inline bool msg_is_neg(int x) { return x < 0; }

inline bool msg_is_nonpos(float x) { return x <= 0.0f; }
inline bool msg_is_nonpos(int x) { return x <= 0; }

inline float msg_from_double(float, double x) { return static_cast<float>(x); }
// Unscaled LLR -> scaled i32 like MinSumBPDecoder: from_f64(S * llr) trunc.
inline int msg_from_double(int, double x) {
  return static_cast<int>(static_cast<double>(kDataScale) * x);
}

// Lambda_j(t) = (1-γ)*λ + γ*M
inline float msg_apply_gamma(float prior, float post_prev, int leg, int v) {
  const float g = kLegGamma[leg][v];
  return prior * (1.0f - g) + post_prev * g;
}
// Match rust compute_variable_prior with data_scale_value=S:
//   (λ/S)*(S-γ) + (M/S)*γ   (integer divide first, then multiply)
inline int msg_apply_gamma(int prior, int post_prev, int leg, int v) {
  const int s = kDataScale;
  const int g = kLegGammaQ[leg][v];
  return (prior / s) * (s - g) + (post_prev / s) * g;
}

struct DetectorWord {
  unsigned char d[kNChk];
};

struct DecodeWord {
  unsigned char decoding[kNVar];
  unsigned char decoded_detectors[kNChk];
  unsigned char success;
  unsigned char iterations;
};

#endif
