// Float32 types and static 3-qubit repetition-code check matrix.
// MsgT = IEEE-754 float32, matching rust RelayDecoder<f32> / RelayDecoderF32.
// See docs/env_setup_notes.md.

#ifndef RELAY_BP_TYPES_HPP
#define RELAY_BP_TYPES_HPP

#include <cmath>
#include <limits>

using MsgT = float;

constexpr int kNVar = 3;
constexpr int kNChk = 2;
constexpr int kMaxChkDeg = 2;
constexpr int kMaxVarDeg = 2;

// Relay-BP-SS (Algorithm 1 / RelayDecoder::decode_detailed):
//   R = kNumLegs = 1 + num_sets = 4  (leg 0 = first Mem-BP + 3 relay sets)
//   T_0 = kPreIter, T_{r>=1} = kSetMaxIter
//   S = kStopNConv = 1 (StoppingCriterion::NConv{stop_after:1})
constexpr int kNumRelaySets = 3;
constexpr int kNumLegs = 1 + kNumRelaySets;  // 4
#ifndef KPRE_ITER_OVERRIDE
constexpr int kPreIter = 10;
#else
constexpr int kPreIter = KPRE_ITER_OVERRIDE;
#endif
constexpr int kSetMaxIter = 10;
constexpr int kStopNConv = 1;
constexpr float kGamma0 = 0.1f;

// Sentinel for "no second-min yet" in min-two magnitudes (Rust: N::max_value()).
// Not a message clip — RelayDecoderF32 leaves max_data_value unset.
constexpr float kMsgAbsSentinel = std::numeric_limits<float>::max();

// Dense H = [[1,1,0],[0,1,1]] as CSR (check -> vars) and CSC (var -> checks).
constexpr int kChkDeg[kNChk] = {2, 2};
constexpr int kChkVars[kNChk][kMaxChkDeg] = {{0, 1}, {1, 2}};

constexpr int kVarDeg[kNVar] = {1, 2, 1};
constexpr int kVarChecks[kNVar][kMaxVarDeg] = {{0, 0}, {0, 1}, {1, 0}};

// Per-leg memory strengths γj(r). Generated by export_golden_vectors.py:
//   kLegGamma[0][*] = gamma0 (uniform)
//   kLegGamma[r][*] for r=1..3 = explicit_gammas[r % num_sets][*]
//     matching Rust RelayDecoder::init_next_set(set_idx) indexing.
#include "leg_gamma_table.gen.hpp"

struct DetectorWord {
  unsigned char d[kNChk];
};

struct DecodeWord {
  unsigned char decoding[kNVar];
  unsigned char decoded_detectors[kNChk];
  unsigned char success;
  unsigned char iterations;
};

#endif
